# Generated by Django 4.0.4 on 2023-06-21 01:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_alter_comuna_nombrecomuna_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='nombreRol',
            field=models.CharField(choices=[('Paciente', 'Paciente'), ('Medico', 'Medico')], default='Paciente', max_length=25, verbose_name='El nombre del rol de usuario'),
        ),
        migrations.CreateModel(
            name='HoraTomada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('hora', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('cerrado', 'Cerrado')], default='abierto', max_length=10)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='horas_doctor', to=settings.AUTH_USER_MODEL, verbose_name='Medico')),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='horas_paciente', to=settings.AUTH_USER_MODEL, verbose_name='Paciente')),
            ],
        ),
    ]
