# Generated by Django 4.2.1 on 2023-06-21 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_rol_nombrerol_horatomada'),
    ]

    operations = [
        migrations.RenameField(
            model_name='horatomada',
            old_name='paciente',
            new_name='nombrePaciente',
        ),
        migrations.AddField(
            model_name='horatomada',
            name='apellidoPaciente',
            field=models.CharField(max_length=50, null=True, verbose_name='Apellido del paciente'),
        ),
        migrations.AddField(
            model_name='horatomada',
            name='nombreComuna',
            field=models.CharField(max_length=50, null=True, verbose_name='Correo del paciente'),
        ),
    ]
