# Generated by Django 4.2.1 on 2023-06-21 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_paciente_horatomada_nombrepaciente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horatomada',
            name='correoPaciente',
            field=models.CharField(max_length=50, null=True, verbose_name='Correo del paciente'),
        ),
        migrations.AlterField(
            model_name='horatomada',
            name='nombreComuna',
            field=models.CharField(max_length=50, null=True, verbose_name='Comuna del paciente'),
        ),
    ]
