# Generated by Django 4.2.2 on 2023-06-22 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_rol_nombrerol'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrePaciente', models.CharField(max_length=50, null=True, verbose_name='Nombre del paciente')),
                ('apellidoPaciente', models.CharField(max_length=50, null=True, verbose_name='Apellido del paciente')),
                ('correoPaciente', models.CharField(max_length=50, null=True, verbose_name='Correo del paciente')),
                ('motivo', models.CharField(max_length=50, null=True, verbose_name='motivo de la consulta')),
                ('diagnostico', models.TextField(null=True, verbose_name='Diagnostico del tratamiento')),
                ('medicamentos', models.TextField(null=True, verbose_name='Medicamentos del tratamiento')),
            ],
        ),
    ]
