# Generated by Django 4.2.2 on 2023-06-22 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_fichamedica'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichamedica',
            name='hora_tomada',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fichas_medicas', to='core.horatomada', verbose_name='Hora tomada'),
        ),
    ]
